name: github pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    deploy-pages:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - name: install tools
          run: |
            rustup target install wasm32-unknown-unknown
            cargo install wasm-bindgen-cli@0.2.92
        - name: build
          run: |
            cargo build --release --target wasm32-unknown-unknown --example interaction
            wasm-bindgen --target web --out-dir ./out/ --out-name bevy-fluid-sample ./target/wasm32-unknown-unknown/release/examples/interaction.wasm
        - uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: .
            publish_branch: pages